Repository MESH-Research/Pilcrow, pull requests merged in 2021-03, with the labels that each got.

#153 fix: resolve console error on page load
  client/src/layouts/App.vue
  client/src/router/routes.js
Labels: frontend

#152 chore: create deployment dockerfiles for preview builds
  backend/.docker/docker-php-entrypoint
  backend/.docker/prepare_ccr
  backend/Dockerfile
  backend/app/Providers/AppServiceProvider.php
  backend/config/app.php
  backend/config/sanctum.php
  client/.docker/default.conf.template
  client/Dockerfile
  containers/docker-compose.yaml
  containers/nginx/10-ssl.sh
  containers/nginx/Dockerfile
  containers/nginx/default.conf.template
  containers/node/Dockerfile
  docker-compose.yaml
  docs/contributing/README.md
  docs/contributing/images/preview_in_progress.jpg
  docs/contributing/images/preview_ready.jpg
Labels: NFR

#163 style(api): add database dir to phpcs checks and fix existing
  backend/database/factories/PermissionFactory.php
  backend/database/factories/RoleFactory.php
  backend/database/factories/UserFactory.php
  backend/database/seeders/DatabaseSeeder.php
  phpcs.xml
Labels: NFR, backend

#166 fix(client,deps): upgrade dependencies to address elliptic CVE
  client/yarn.lock
Labels: dependencies, frontend

#167 fix(docs,deps): upgrade dependencies to address cve-2020-28498
  docs/package.json
  docs/yarn.lock
Labels: dependencies, documentation

#189 fix: resolve outstanding accessibility issues
  client/src/components/AppHeader.vue
  client/src/components/atoms/EmailVerificationSendButton.vue
  client/src/components/molecules/EmailVerificationBanner.vue
  client/src/css/app.sass
  client/src/css/quasar.variables.sass
  client/src/layouts/MainLayout.vue
  client/src/pages/Account/AccountLayout.vue
  client/src/pages/Account/Profile.vue
  client/src/pages/Admin/UsersIndex.vue
  client/src/pages/Dashboard.vue
  client/src/pages/Index.vue
  client/src/pages/Login.vue
  client/src/pages/Register.vue
  client/test/cypress/integration/account.spec.js
  client/test/cypress/integration/admin/users.spec.js
  client/test/cypress/integration/dashboard.spec.js
  client/test/cypress/integration/header.spec.js
  client/test/cypress/integration/home.spec.js
  client/test/cypress/integration/login.spec.js
  client/test/cypress/integration/register.spec.js
Labels: pr-preview
